### ISSUE TITLE
"Current Line" and "Selected Text" should have different colors

### ISSUE THREAD

**Issue by dharmaturtle** [kritzware/json.pizza#1]
![image](https://user-images.githubusercontent.com/1278803/51797350-516fca00-21c7-11e9-9a03-93e8713c45ab.png)

You can't tell, but I have the word "Print" selected. The active/current line and the highlighted/selected text have the same color background, and I think they should be different.

Thanks for a useful website!

**Comment by kritzware** [comment]
That's a good point, thanks for making an issue! 

I'll look into it, thanks 😄

**Comment by kritzware** [comment]
This was due to the `dracula` theme not working correctly. I couldn't find a fix, so I've changed the theme to `vibrant_ink`, which now highlights words in a visible colour.
