### ISSUE TITLE
CTRL + L just highlights the URL Bar

### ISSUE THREAD

**Issue by Qoyyuum** [kritzware/json.pizza#2]
I think its a standard browser shortcut in Firefox and Edge (I have not tested in Chrome) to focus on the URL Bar when using this shortcut. Please remap it to `CTRL + Shift + L` perhaps.

**Comment by kritzware** [comment]
The feature that used `CTRL + L` was actually removed, but if it's ever added back I will make sure to use `Shift` 👍
