### ISSUE TITLE
WEBSITE IS DOWN 🔥😭

### ISSUE THREAD

**Issue by rijkvanzanten** [kritzware/json.pizza#21]
![image](https://user-images.githubusercontent.com/9141017/72167649-89046180-3399-11ea-9fd7-55438e667524.png)

**Comment by kritzware** [comment]
Looks like Netlify (our provider) is having some issues! Nothing we can do here, so we'll just have to wait for them to resolve the issue 👍

**Comment by rijkvanzanten** [comment]
Yikes.. there's no reported issues on Netlify's side though (https://www.netlifystatus.com/), could it be a DNS issue?

**Comment by kritzware** [comment]
My companies app was also down (which uses Netlify), so I assume some Netlify DNS issue.

**Comment by kritzware** [comment]
Looks like it should be resolved now. It might just take a short while for changes to propagate.

**Comment by rijkvanzanten** [comment]
Pfew, crisis averted. All good on my end too 👍
